name: Build, Test, and Push Docker Image

on:
  push:
    branches:
      - develop

env:
  JAVA_VERSION: '17'

jobs:
  setup-jdk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ env.JAVA_VERSION }}

  run-tests:
    needs: setup-jdk
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ env.JAVA_VERSION }}

      - name: Run Unit Tests
        run: mvn test

      - name: Generate Test Report
        run: mvn surefire-report:report-only

      - name: Upload Test Report as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: test-report
          path: target/surefire-reports

  build-package:
    needs: run-tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ env.JAVA_VERSION }}

      - name: Build with Maven
        run: mvn clean package -Pprd

  build-and-push-image:
    needs: build-package
    runs-on: ubuntu-latest

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: dasilvathaynara/ez-fast-food-api:latest

# Optional Deploy Job
# deploy:
#   needs: build-and-push-image
#   runs-on: ubuntu-latest
#
#   steps:
#   - name: Checkout repository
#     uses: actions/checkout@v3
#
#   - name: Set Kubernetes context
#     run: kubectl config set-context --current --namespace=default
#
#   - name: Apply Kubernetes manifests
#     run: kubectl apply -f k8s/
